### PR TITLE
allow unicode (utf8) and everything in values

### PR DESCRIPTION
**Pull request by brigadier**
Allow everything in values, including valid and invalid utf-8 data.

### CODE REVIEW

**Comment by motobob** [comment]
lgtm. @waisbrot any objections?
What was the motivation for the change ? 
do you wish this to be incorporated into `erlcloud` library?

**Comment by nalundgaard** [comment]
The unit test added appears to fail in travis. This should at the very least be made to work prior to merging.

**Comment by waisbrot** [comment]
The unit test failure was because Travis runs Rebar2 and Rebar2 and Rebar3 appear to have different working directories, so `file:read_file("tests/test.txt")` fails under Rebar2. I just pasted in the results as a work-around to that (trying out that new semi-public PRs feature; I hope you don't mind @brigadier).

Looks like there's still a failure. It reads like R16 just doesn't handle UTF8 the same way as later versions.

This could be useful if someone had multiple AWS profiles and they gave them UTF8 names (seems unlikely pot possible). It's more likely to be useful if eini is needed as a general INI-parser library.

In principle, UTF8 everywhere is great and we should do it. In practice, I feel like this won't affect many users.

@motobob a nice thing to add to the roadmap would be planned support for various older versions of Erlang. If we don't need to support R16, I'd like to drop it from our tests and accept this PR.

**Comment by brigadier** [comment]
Wait for a while, I'll rewrite the tests to be compatible with R16

**Comment by brigadier** [comment]
All tests have passed successfully now.

> What was the motivation for the change ?

A configurable welcome message in one of my projects, a certain user asked for non-ascii one.

> do you wish this to be incorporated into erlcloud library?

I don't care tbh.

**Comment by waisbrot** [comment]
Thanks!

**Comment by nalundgaard** [comment]
Cool, thanks @brigadier!

**Pull request merged**
